=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module OpenapiClient
  # The `FineTune` object represents a legacy fine-tune job that has been created through the API. 
  class KolideFineTune
    # The object identifier, which can be referenced in the API endpoints.
    attr_accessor :id

    # The Unix timestamp (in seconds) for when the fine-tuning job was created.
    attr_accessor :created_at

    # The list of events that have been observed in the lifecycle of the FineTune job.
    attr_accessor :events

    # The name of the fine-tuned model that is being created.
    attr_accessor :fine_tuned_model

    attr_accessor :hyperparams

    # The base model that is being fine-tuned.
    attr_accessor :model

    # The object type, which is always \"fine-tune\".
    attr_accessor :object

    # The organization that owns the fine-tuning job.
    attr_accessor :organization_id

    # The compiled results files for the fine-tuning job.
    attr_accessor :result_files

    # The current status of the fine-tuning job, which can be either `created`, `running`, `succeeded`, `failed`, or `cancelled`.
    attr_accessor :status

    # The list of files used for training.
    attr_accessor :training_files

    # The Unix timestamp (in seconds) for when the fine-tuning job was last updated.
    attr_accessor :updated_at

    # The list of files used for validation.
    attr_accessor :validation_files

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'created_at' => :'created_at',
        :'events' => :'events',
        :'fine_tuned_model' => :'fine_tuned_model',
        :'hyperparams' => :'hyperparams',
        :'model' => :'model',
        :'object' => :'object',
        :'organization_id' => :'organization_id',
        :'result_files' => :'result_files',
        :'status' => :'status',
        :'training_files' => :'training_files',
        :'updated_at' => :'updated_at',
        :'validation_files' => :'validation_files'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'created_at' => :'Integer',
        :'events' => :'Array<KolideFineTuneEvent>',
        :'fine_tuned_model' => :'String',
        :'hyperparams' => :'KolideFineTuneHyperparams',
        :'model' => :'String',
        :'object' => :'String',
        :'organization_id' => :'String',
        :'result_files' => :'Array<KolideOpenAIFile>',
        :'status' => :'String',
        :'training_files' => :'Array<KolideOpenAIFile>',
        :'updated_at' => :'Integer',
        :'validation_files' => :'Array<KolideOpenAIFile>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'fine_tuned_model',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::KolideFineTune` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::KolideFineTune`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'events')
        if (value = attributes[:'events']).is_a?(Array)
          self.events = value
        end
      end

      if attributes.key?(:'fine_tuned_model')
        self.fine_tuned_model = attributes[:'fine_tuned_model']
      else
        self.fine_tuned_model = nil
      end

      if attributes.key?(:'hyperparams')
        self.hyperparams = attributes[:'hyperparams']
      else
        self.hyperparams = nil
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      else
        self.model = nil
      end

      if attributes.key?(:'object')
        self.object = attributes[:'object']
      else
        self.object = nil
      end

      if attributes.key?(:'organization_id')
        self.organization_id = attributes[:'organization_id']
      else
        self.organization_id = nil
      end

      if attributes.key?(:'result_files')
        if (value = attributes[:'result_files']).is_a?(Array)
          self.result_files = value
        end
      else
        self.result_files = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'training_files')
        if (value = attributes[:'training_files']).is_a?(Array)
          self.training_files = value
        end
      else
        self.training_files = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'validation_files')
        if (value = attributes[:'validation_files']).is_a?(Array)
          self.validation_files = value
        end
      else
        self.validation_files = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @hyperparams.nil?
        invalid_properties.push('invalid value for "hyperparams", hyperparams cannot be nil.')
      end

      if @model.nil?
        invalid_properties.push('invalid value for "model", model cannot be nil.')
      end

      if @object.nil?
        invalid_properties.push('invalid value for "object", object cannot be nil.')
      end

      if @organization_id.nil?
        invalid_properties.push('invalid value for "organization_id", organization_id cannot be nil.')
      end

      if @result_files.nil?
        invalid_properties.push('invalid value for "result_files", result_files cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @training_files.nil?
        invalid_properties.push('invalid value for "training_files", training_files cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @validation_files.nil?
        invalid_properties.push('invalid value for "validation_files", validation_files cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @created_at.nil?
      return false if @hyperparams.nil?
      return false if @model.nil?
      return false if @object.nil?
      object_validator = EnumAttributeValidator.new('String', ["fine-tune"])
      return false unless object_validator.valid?(@object)
      return false if @organization_id.nil?
      return false if @result_files.nil?
      return false if @status.nil?
      return false if @training_files.nil?
      return false if @updated_at.nil?
      return false if @validation_files.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] object Object to be assigned
    def object=(object)
      validator = EnumAttributeValidator.new('String', ["fine-tune"])
      unless validator.valid?(object)
        fail ArgumentError, "invalid value for \"object\", must be one of #{validator.allowable_values}."
      end
      @object = object
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          created_at == o.created_at &&
          events == o.events &&
          fine_tuned_model == o.fine_tuned_model &&
          hyperparams == o.hyperparams &&
          model == o.model &&
          object == o.object &&
          organization_id == o.organization_id &&
          result_files == o.result_files &&
          status == o.status &&
          training_files == o.training_files &&
          updated_at == o.updated_at &&
          validation_files == o.validation_files
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, created_at, events, fine_tuned_model, hyperparams, model, object, organization_id, result_files, status, training_files, updated_at, validation_files].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
