=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::FineTunesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FineTunesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::FineTunesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FineTunesApi' do
    it 'should create an instance of FineTunesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::FineTunesApi)
    end
  end

  # unit tests for cancel_fine_tune
  # Immediately cancel a fine-tune job. 
  # @param fine_tune_id The ID of the fine-tune job to cancel 
  # @param [Hash] opts the optional parameters
  # @return [FineTune]
  describe 'cancel_fine_tune test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_fine_tune
  # Creates a job that fine-tunes a specified model from a given dataset.  Response includes details of the enqueued job including job status and the name of the fine-tuned models once complete.  [Learn more about fine-tuning](/docs/guides/legacy-fine-tuning) 
  # @param create_fine_tune_request 
  # @param [Hash] opts the optional parameters
  # @return [FineTune]
  describe 'create_fine_tune test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_fine_tune_events
  # Get fine-grained status updates for a fine-tune job. 
  # @param fine_tune_id The ID of the fine-tune job to get events for. 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :stream Whether to stream events for the fine-tune job. If set to true, events will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available. The stream will terminate with a &#x60;data: [DONE]&#x60; message when the job is finished (succeeded, cancelled, or failed).  If set to false, only events generated so far will be returned. 
  # @return [ListFineTuneEventsResponse]
  describe 'list_fine_tune_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_fine_tunes
  # List your organization&#39;s fine-tuning jobs 
  # @param [Hash] opts the optional parameters
  # @return [ListFineTunesResponse]
  describe 'list_fine_tunes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_fine_tune
  # Gets info about the fine-tune job.  [Learn more about fine-tuning](/docs/guides/legacy-fine-tuning) 
  # @param fine_tune_id The ID of the fine-tune job 
  # @param [Hash] opts the optional parameters
  # @return [FineTune]
  describe 'retrieve_fine_tune test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
