=begin
#OpenAI API

#The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::KolideChatCompletionRole
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::KolideChatCompletionRole do
  let(:instance) { OpenapiClient::KolideChatCompletionRole.new }

  describe 'test an instance of KolideChatCompletionRole' do
    it 'should create an instance of KolideChatCompletionRole' do
      expect(instance).to be_instance_of(OpenapiClient::KolideChatCompletionRole)
    end
  end
end
